# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.13.0
        with:
         channel: 'stable'

      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - run: flutter build ios
